[package]
edition = "2024"
name = "server_types"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror = {version = "=1.0.48"}
sqlx.workspace = true
utoipa = {version = "=4.1.0", features = ["axum_extras"]}
schemars = {version = "=0.8.22"}
uuid.workspace = true
error_occurence_lib = {path = "../error_occurence_lib"}
postgresql_crud = {path = "../postgresql_crud", features = ["test-utils"]}

[lints]
workspace = true

[features]
test-utils = ["postgresql_crud/test-utils"]