[package]
edition = "2024"
name = "server_types"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "=0.7.4", features = ["macros"]}
chrono = {version = "=0.4.42", features = ["serde"]}
dotenv = {version = "=0.15.0"}
http = {version = "=0.2.9"}
reqwest = {version = "=0.11.17", default-features = false, features = ["json", "blocking", "rustls-tls", "cookies", "gzip", "brotli", "deflate", "trust-dns", "native-tls", "multipart", "stream", "cookies"]}
secrecy = {version = "=0.8.0", features = ["serde"]}
serde = {version = "=1.0.224", features = ["derive"]}
serde_derive = {version = "=1.0.224"}
serde_json = {version = "=1.0.145"}
thiserror = {version = "=1.0.48"}
tokio = {version = "=1.29.1", features = ["macros", "rt-multi-thread"]}
sqlx = {version = "=0.8.5", features = ["postgres", "uuid", "bigdecimal", "rust_decimal", "chrono", "time", "bit-vec", "runtime-tokio", "ipnetwork", "mac_address", "bit-vec", "json"]}
tracing-subscriber = {version = "=0.3.22", features = ["registry", "env-filter"]}
utoipa = {version = "=4.1.0", features = ["axum_extras"]}
schemars = {version = "=0.8.22"}
uuid = {version = "=1.10.0", features = ["serde", "v4"]}
git_info = {path = "../git_info"}
error_occurence_lib = {path = "../error_occurence_lib"}
postgresql_crud = {path = "../postgresql_crud", features = ["test-utils"]}
config_lib = {path = "../config_lib"}
app_state = {path = "../app_state"}
common_routes = {path = "../common_routes"}

[dev-dependencies]
num_cpus = {version = "=1.15.0"}
futures = {version = "=0.3.28"}

[lints]
workspace = true

[features]
test-utils = ["postgresql_crud/test-utils"]