[package]
edition = "2024"
name = "server_types"
version = "0.1.0"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
sqlx.workspace = true
utoipa.workspace = true
schemars.workspace = true
uuid.workspace = true
error_occurence_lib = {path = "../error_occurence_lib"}
postgres_crud = {path = "../postgres_crud", features = ["test-utils"]}

[lints]
workspace = true

[features]
test-utils = ["postgres_crud/test-utils"]