[package]
name = "server_port"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
server_port_try_from_u16 = {path = "./server_port_try_from_u16"}
server_port_common = {path = "./server_port_common"}

[lints]
workspace = true