[package]
name = "generate_postgresql_types_test_content"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[lints]
workspace = true