[package]
name = "pg_types_common"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
sqlx.workspace = true
serde.workspace = true
utoipa.workspace = true
thiserror.workspace = true
schemars.workspace = true
pg_crud_common = {path = "../../pg_crud_common", features = ["test-utils"]}
er_occurence_lib = {path = "../../../er_occurence_lib"}

[lints]
workspace = true