[package]
name = "generate_postgresql_json_object_type"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
strum.workspace = true
strum_macros.workspace = true
serde.workspace = true
serde_json.workspace = true
postgresql_crud_macros_common = {path = "../../postgresql_crud_macros_common"}
constants = {path = "../../../constants"}
generate_quotes = {path = "../../../generate_quotes"}
panic_location = {path = "../../../panic_location"}
naming = {path = "../../../naming"}
macros_helpers = {path = "../../../macros_helpers"}
token_patterns = {path = "../../../token_patterns"}
enum_extension_lib = {path = "../../../enum_extension_lib"}

[lints]
workspace = true
