[package]
name = "postgresql_json_types"
version = "0.1.0"
edition = "2024"

[dependencies]
generate_postgresql_json_types = {path = "./generate_postgresql_json_types"}
uuid.workspace = true
utoipa = {version = "=4.1.0", features = ["axum_extras"]}
sqlx.workspace = true
serde.workspace = true
schemars = {version = "=0.8.22"}
error_occurence_lib = {path = "../../error_occurence_lib"}
postgresql_crud_common = {path = "../postgresql_crud_common", features = ["test-utils"]}
where_filters = {path = "../where_filters"}

[lints]
workspace = true

[features]
test-utils = ["postgresql_crud_common/test-utils"]