[package]
name = "postgresql_json_types"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
uuid.workspace = true
utoipa.workspace = true
sqlx.workspace = true
serde.workspace = true
schemars.workspace = true
generate_postgresql_json_types = {path = "./generate_postgresql_json_types"}
error_occurence_lib = {path = "../../error_occurence_lib"}
postgresql_crud_common = {path = "../postgresql_crud_common", features = ["test-utils"]}
where_filters = {path = "../where_filters"}

[lints]
workspace = true

[features]
test-utils = ["postgresql_crud_common/test-utils"]