[package]
name = "naming"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = {version = "=1.0.81"}
quote = {version = "=1.0.36"}
syn = {version = "=2.0.60"}
constants = {path = "../constants"}
generate_quotes = {path = "../generate_quotes"}
naming_macros = {path = "./naming_macros"}
naming_common = {path = "./naming_common"}

[lints]
workspace = true
