[package]
name = "generate_where_filters"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
postgresql_crud_macros_common = {path = "../../postgresql_crud_macros_common"}
generate_quotes = {path = "../../../generate_quotes"}
panic_location = {path = "../../../panic_location"}
naming = {path = "../../../naming"}
token_patterns = {path = "../../../token_patterns"}
macros_helpers = {path = "../../../macros_helpers"}

[lints]
workspace = true