[package]
name = "generate_postgresql_table_test"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dev-dependencies]
proc-macro2.workspace = true
quote.workspace = true
generate_postgresql_table_source = {path = "../generate_postgresql_table_source"}
macro_clippy_check_common = {path = "../../../macro_clippy_check_common"}

[lints]
workspace = true

[features]
test-utils = ["macro_clippy_check_common/test-utils"]