[package]
name = "error_occurence_test"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
error_occurence_lib = {path = "../error_occurence_lib"}

[lints]
workspace = true
