[package]
name = "generate_struct_or_enum_derive_ts_builder"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
serde_json.workspace = true
naming = {path = "../../naming"}

[lints]
workspace = true