[package]
edition = "2024"
name = "try_from_env"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
constants = {path = "../../constants"}
panic_location = {path = "../../panic_location"}
naming = {path = "../../naming"}
macros_helpers = {path = "../../macros_helpers"}

[lints]
workspace = true