[package]
name = "gen_where_filters"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
serde.workspace = true
serde_json.workspace = true
pg_crud_macros_common = {path = "../../pg_crud_macros_common"}
gen_quotes = {path = "../../../gen_quotes"}
panic_location = {path = "../../../panic_location"}
naming = {path = "../../../naming"}
token_patterns = {path = "../../../token_patterns"}
macros_helpers = {path = "../../../macros_helpers"}

[lints]
workspace = true