[package]
name = "postgresql_crud_common_and_macros_common"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = {version = "=1.0.95"}
quote = {version = "=1.0.36"}
serde.workspace = true
schemars = {version = "=0.8.22"}
naming = {path = "../../naming"}

[lints]
workspace = true