[package]
name = "gen_postgresql_table_source"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
strum_macros.workspace = true
serde.workspace = true
serde_json.workspace = true
gen_quotes = {path = "../../../gen_quotes"}
panic_location = {path = "../../../panic_location"}
macros_helpers = {path = "../../../macros_helpers"}
naming = {path = "../../../naming"}
token_patterns = {path = "../../../token_patterns"}
postgresql_crud_macros_common = {path = "../../postgresql_crud_macros_common"}

[lints]
workspace = true