[package]
name = "to_std_string_string"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = {version = "=0.1.43", features = ["log", "valuable"]}
reqwest.workspace = true
http-body = {version = "=1.0.0"}
axum = {version = "=0.7.4", features = ["macros"]}
time = {version = "=0.3.36", features = ["serde"]}
sqlx.workspace = true
serde_json.workspace = true
http = {version = "=0.2.9"}

[lints]
workspace = true
