[package]
name = "to_std_string_string"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = {version = "=0.1", features = ["log", "valuable"]}
reqwest = {version = "=0.11.17", default-features = false, features = ["json", "blocking", "rustls-tls", "cookies", "gzip", "brotli", "deflate", "trust-dns", "native-tls", "multipart", "stream", "cookies"]}
http-body = {version = "=1.0.0"}
axum = {version = "=0.7.4", features = ["macros"]}
time = {version = "=0.3.36", features = ["serde"]}
sqlx = {version = "=0.7.3", features = ["postgres", "uuid", "bigdecimal", "rust_decimal", "chrono", "time", "bit-vec", "runtime-tokio", "ipnetwork", "mac_address", "bit-vec", "json"]}
serde_json = {version = "=1.0"}
http = {version = "=0.2.9"}

[lints]
workspace = true
