[package]
name = "to_std_string_string"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing.workspace = true
reqwest.workspace = true
http-body.workspace = true
axum.workspace = true
time.workspace = true
sqlx.workspace = true
serde_json.workspace = true
http.workspace = true

[lints]
workspace = true
