[package]
name = "postgresql_types"
version = "0.1.0"
edition = "2024"

[dependencies]
generate_postgresql_types = {path = "./generate_postgresql_types"}
postgresql_crud_common = {path = "../postgresql_crud_common", features = ["test-utils"]}
sqlx.workspace = true
serde.workspace = true
chrono = {version = "=0.4.42", features = ["serde"]}
error_occurence_lib = {path = "../../error_occurence_lib"}
where_filters = {path = "../where_filters"}
utoipa = {version = "=4.1.0", features = ["axum_extras"]}
thiserror = {version = "=1.0.48"}
schemars = {version = "=0.8.22"}

[lints]
workspace = true

[features]
test-utils = ["postgresql_crud_common/test-utils"]