[package]
name = "generate_postgresql_json_types"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
generate_postgresql_json_types_source = {path = "../generate_postgresql_json_types_source"}

[lints]
workspace = true