[package]
name = "generate_postgresql_json_types"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
strum.workspace = true
strum_macros.workspace = true
# schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
rayon.workspace = true
postgresql_crud_macros_common = {path = "../../postgresql_crud_macros_common"}
enum_extension_lib = {path = "../../../enum_extension_lib"}
generate_quotes = {path = "../../../generate_quotes"}
panic_location = {path = "../../../panic_location"}
macros_helpers = {path = "../../../macros_helpers"}
naming = {path = "../../../naming"}
token_patterns = {path = "../../../token_patterns"}

[lints]
workspace = true