[package]
name = "gen_postgresql_json_object_type_test"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dev-dependencies]
quote.workspace = true
gen_postgresql_json_object_type_source = {path = "../gen_postgresql_json_object_type_source"}
macro_clippy_check_common = {path = "../../../macro_clippy_check_common"}

[lints]
workspace = true

[features]
test-utils = ["macro_clippy_check_common/test-utils"]