[package]
name = "generate_postgresql_types"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote = {version = "=1.0.36"}
serde.workspace = true
serde_json.workspace = true
strum = {version = "=0.24.1"}
strum_macros = {version = "=0.24.3"}
rayon = {version = "=1.10.0"}
postgresql_crud_macros_common = {path = "../../postgresql_crud_macros_common"}
postgresql_crud_common_and_macros_common = {path = "../../postgresql_crud_common_and_macros_common"}
enum_extension_lib = {path = "../../../enum_extension_lib"}
generate_quotes = {path = "../../../generate_quotes"}
panic_location = {path = "../../../panic_location"}
macros_helpers = {path = "../../../macros_helpers"}
naming = {path = "../../../naming"}
token_patterns = {path = "../../../token_patterns"}

[lints]
workspace = true