[package]
name = "postgres_table"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
gen_postgres_table = {path = "./gen_postgres_table"}
app_state = {path = "../../app_state"}

[lints]
workspace = true

[features]
test-utils = []