[package]
name = "naming_common"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
convert_case.workspace = true
constants = {path = "../../constants"}

[lints]
workspace = true