[package]
name = "naming_common"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
convert_case.workspace = true
constants = {path = "../../constants"}

[lints]
workspace = true