[package]
name = "where_filters"
version = "0.1.0"
edition = "2024"

[dependencies]
generate_where_filters = {path = "./generate_where_filters"}
sqlx = {version = "=0.8.5", features = ["postgres", "uuid", "bigdecimal", "rust_decimal", "chrono", "time", "bit-vec", "runtime-tokio", "ipnetwork", "mac_address", "bit-vec", "json"]}
serde.workspace = true
schemars = {version = "=0.8.22"}
error_occurence_lib = {path = "../../error_occurence_lib"}
postgresql_crud_common = {path = "../postgresql_crud_common", features = ["test-utils"]}
utoipa = {version = "=4.1.0", features = ["axum_extras"]}
regex.workspace = true
thiserror = {version = "=1.0.48"}

[lints]
workspace = true

[features]
test-utils = ["postgresql_crud_common/test-utils"]