[package]
edition = "2024"
name = "error_occurence"
version = "0.1.0"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
macros_helpers = {path = "../../macros_helpers"}
constants = {path = "../../constants"}
generate_quotes = {path = "../../generate_quotes"}
panic_location = {path = "../../panic_location"}
token_patterns = {path = "../../token_patterns"}
naming = {path = "../../naming"}

[lints]
workspace = true
