[package]
name = "integration_tests"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
serde = {version = "=1.0.224", features = ["derive"]}
toml = {version = "=0.9.6"}

[lints]
workspace = true
