[package]
name = "route_validators"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum.workspace = true
thiserror.workspace = true
serde.workspace = true
http-body.workspace = true
bytes.workspace = true
git_info = {path = "../git_info"}
naming = {path = "../naming"}
error_occurence_lib = {path = "../error_occurence_lib"}
http_logic = {path = "../http_logic"}

[lints]
workspace = true
