[package]
name = "route_validators"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = {version = "=0.7.4", features = ["macros"]}
thiserror = {version = "=1.0.48"}
serde = {version = "=1.0", features = ["derive"]}
http-body = {version = "=1.0.0"}
bytes = {version = "=1.2.1"}
git_info = {path = "../git_info"}
naming = {path = "../naming"}
error_occurence_lib = {path = "../error_occurence_lib"}
http_logic = {path = "../http_logic"}

[lints]
workspace = true
