[package]
name = "postgres_json_object_type_common"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
utoipa.workspace = true
serde.workspace = true
thiserror.workspace = true
schemars.workspace = true
error_occurence_lib = {path = "../../../error_occurence_lib"}
postgres_crud_common = {path = "../../postgres_crud_common", features = ["test-utils"]}

[lints]
workspace = true

[features]
test-utils = ["postgres_crud_common/test-utils"]