[package]
name = "server_table_example"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "=0.7.4", features = ["macros"]}
http = {version = "=0.2.9"}
reqwest = {version = "=0.11.17", default-features = false, features = ["json", "blocking", "rustls-tls", "cookies", "gzip", "brotli", "deflate", "trust-dns", "native-tls", "multipart", "stream", "cookies"]}
serde = {version = "=1.0.224", features = ["derive"]}
serde_json = {version = "=1.0.145"}
thiserror = {version = "=1.0.48"}
sqlx = {version = "=0.8.5", features = ["postgres", "uuid", "bigdecimal", "rust_decimal", "chrono", "time", "bit-vec", "runtime-tokio", "ipnetwork", "mac_address", "bit-vec", "json"]}
utoipa = {version = "=4.1.0", features = ["axum_extras"]}
git_info = {path = "../git_info"}
error_occurence_lib = {path = "../error_occurence_lib"}
postgresql_crud = {path = "../postgresql_crud", features = ["test-utils"]}
server_types = {path = "../server_types"}

[dev-dependencies]
num_cpus = {version = "=1.15.0"}
futures = {version = "=0.3.28"}
app_state = {path = "../app_state"}
config_lib = {path = "../config_lib"}
secrecy = {version = "=0.8.0", features = ["serde"]}
server_app_state = {path = "../server_app_state"}
server_config = {path = "../server_config"}
tokio = {version = "=1.29.1", features = ["macros", "rt-multi-thread"]}
tracing-subscriber = {version = "=0.3.22", features = ["registry", "env-filter"]}
uuid = {version = "=1.10.0", features = ["serde", "v4"]}

[lints]
workspace = true

[features]
test-utils = ["postgresql_crud/test-utils"]