[package]
name = "server_table_example"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
axum.workspace = true
http.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
sqlx.workspace = true
utoipa.workspace = true
git_info = {path = "../git_info"}
er_occurence_lib = {path = "../er_occurence_lib"}
pg_crud = {path = "../pg_crud", features = ["test-utils"]}
server_types = {path = "../server_types"}

[dev-dependencies]
num_cpus.workspace = true
futures.workspace = true
secrecy.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
uuid.workspace = true
itertools.workspace = true
app_state = {path = "../app_state"}
config_lib = {path = "../config_lib"}
server_app_state = {path = "../server_app_state"}
server_config = {path = "../server_config"}

[lints]
workspace = true

[features]
test-utils = ["pg_crud/test-utils"]