[package]
name = "server_table_example"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = {version = "=0.7.4", features = ["macros"]}
http = {version = "=0.2.9"}
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror = {version = "=1.0.48"}
sqlx.workspace = true
utoipa = {version = "=4.1.0", features = ["axum_extras"]}
git_info = {path = "../git_info"}
error_occurence_lib = {path = "../error_occurence_lib"}
postgresql_crud = {path = "../postgresql_crud", features = ["test-utils"]}
server_types = {path = "../server_types"}

[dev-dependencies]
num_cpus = {version = "=1.15.0"}
futures = {version = "=0.3.28"}
app_state = {path = "../app_state"}
config_lib = {path = "../config_lib"}
secrecy = {version = "=0.8.0", features = ["serde"]}
server_app_state = {path = "../server_app_state"}
server_config = {path = "../server_config"}
tokio.workspace = true
tracing-subscriber = {version = "=0.3.22", features = ["registry", "env-filter"]}
uuid.workspace = true

[lints]
workspace = true

[features]
test-utils = ["postgresql_crud/test-utils"]