[package]
name = "pg_crud_common"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
utoipa.workspace = true
uuid.workspace = true
sqlx.workspace = true
serde.workspace = true
thiserror.workspace = true
schemars.workspace = true
location_lib = {path = "../../location_lib"}
from_str = {path = "../../from_str"}
naming = {path = "../../naming"}
pg_crud_common_and_macros_common = {path = "../pg_crud_common_and_macros_common"}

[features]
test-utils = []

[lints]
workspace = true