[package]
name = "postgres_crud"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum_macros.workspace = true
futures.workspace = true
uuid.workspace = true
postgres_crud_common = {path = "./postgres_crud_common", features = ["test-utils"]}
postgres_table = {path = "./postgres_table"}
postgres_json_object_type = {path = "./postgres_json_object_type"}
postgres_json_types = {path = "./postgres_json_types"}
postgres_types = {path = "./postgres_types"}
where_filters = {path = "./where_filters"}
route_validators = {path = "../route_validators"}

[lints]
workspace = true

[features]
test-utils = [
    "postgres_crud_common/test-utils",
    "postgres_table/test-utils",
    "postgres_json_types/test-utils",
    "postgres_types/test-utils",
    "where_filters/test-utils"
]
