[package]
name = "postgresql_table"
version = "0.1.0"
edition = "2024"

[dependencies]
generate_postgresql_table = {path = "./generate_postgresql_table"}
app_state = {path = "../../app_state"}

[lints]
workspace = true

[features]
test-utils = []