[package]
name = "server_config"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono.workspace = true
thiserror.workspace = true
dotenv.workspace = true
secrecy.workspace = true
config_lib = {path = "../config_lib"}
app_state = {path = "../app_state"}

[lints]
workspace = true
