[package]
name = "gen_pg_types_test"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dev-dependencies]
quote.workspace = true
macro_clippy_check_common = {path = "../../../macro_clippy_check_common"}
gen_pg_types_source = {path = "../gen_pg_types_source"}

[lints]
workspace = true

[features]
test-utils = ["macro_clippy_check_common/test-utils"]