[package]
edition = "2024"
name = "generate_getter_traits_for_struct_fields"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
panic_location = {path = "../../panic_location"}
naming = {path = "../../naming"}

[lints]
workspace = true
