[package]
name = "pg_json_object_type"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
gen_pg_json_object_type = {path = "./gen_pg_json_object_type"}
pg_json_object_type_common = {path = "./pg_json_object_type_common"}
#pg_crud_common = {path = "../pg_crud_common", features = ["test-utils"]}

[lints]
workspace = true

#[features]
#test-utils = ["pg_crud_common/test-utils"]