[package]
edition = "2024"
name = "generate_postgresql_table"
version = "0.1.0"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
# convert_case.workspace = true
strum_macros.workspace = true
constants = {path = "../../../constants"}
generate_quotes = {path = "../../../generate_quotes"}
panic_location = {path = "../../../panic_location"}
macros_helpers = {path = "../../../macros_helpers"}
naming = {path = "../../../naming"}
token_patterns = {path = "../../../token_patterns"}
postgresql_crud_macros_common = {path = "../../postgresql_crud_macros_common"}

[lints]
workspace = true
