[package]
name = "postgresql_json_object_type"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]
generate_postgresql_json_object_type = {path = "./generate_postgresql_json_object_type"}
postgresql_json_object_type_common = {path = "./postgresql_json_object_type_common"}
#postgresql_crud_common = {path = "../postgresql_crud_common", features = ["test-utils"]}

[lints]
workspace = true

#[features]
#test-utils = ["postgresql_crud_common/test-utils"]