[package]
name = "macro_clippy_check_common"
version = "0.1.0"
edition = "2024"
description = "description"
repository = "repository"
readme = "readme"
license = "license"
keywords = ["keyword"]
categories = ["category"]

[dependencies]

[features]
test-utils = []

[lints]
workspace = true