[package]
name = "file_system"
version = "0.1.0"
edition = "2024"

[dependencies]
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
thiserror = {version = "=1.0.48"}
error_occurence_lib = {path = "../error_occurence_lib"}

[lints]
workspace = true
